# Generated by Django 5.2.3 on 2025-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamaño', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('estado_salud', models.CharField(max_length=100)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=10)),
                ('temperamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerroGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerroPequeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('preferencia_raza', models.CharField(blank=True, max_length=100)),
                ('preferencia_tamaño', models.CharField(blank=True, max_length=50)),
                ('preferencia_edad', models.IntegerField(blank=True, null=True)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='gestion.perro')),
            ],
        ),
    ]
