# Generated by Django 5.2.3 on 2025-05-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerroPequeño',
            new_name='PerroAdulto',
        ),
        migrations.RenameModel(
            old_name='PerroGrande',
            new_name='PerroJoven',
        ),
    ]
