# Generated by Django 5.2.3 on 2025-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_perropequeño_perroadulto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
